volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mtoof/data/mariadb_data
      o: bind
  # wordpress_data:
  #   name: wordpress_data
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /wordpress_data
  #     o: bind

networks:
  inception:
    name: inception

services:
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception
  #   depends_on:
  #     - wordpress
  #   env_file: .env
  #   restart: always
  
  # wordpress:
  #   container_name: wordpress
  #   image: wordpress:5.8.2
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: example_password
  #     WORDPRESS_DB_NAME: wordpress
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception
  #   volumes:
  #     - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    image: mymariadb
    build: ./requirements/mariadb/.
    # environment:
      # MYSQL_ROOT_PASSWORD: example_password
      # MYSQL_DATABASE: 
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
