volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mtoof/data/mariadb_data
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/mtoof/data/wordpress_data
      o: bind

networks:
  inception:
    name: inception

services:
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception
  #   depends_on:
  #     - wordpress
  #   env_file: .env
  #   restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress:mtoof
    build: ./requirements/wordpress/.
    env_file:
      .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    command: >
      sh -c '
        until docker inspect -f "{{.State.Running}}" mariadb | grep -q "true"; do
          sleep 10
        done;
        echo "MariaDB is now running"
      '

  mariadb:
    container_name: mariadb
    image: mariadb:mtoof
    build: ./requirements/mariadb/.
    # environment:
      # MYSQL_ROOT_PASSWORD: example_password
      # MYSQL_DATABASE: 
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql